[build]
  base = "frontend"
  command = "pnpm build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "^25"
  PNPM_VERSION = "^10"

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true
