import {
  mdiAccountBadgeOutline,
  mdiAccountGroupOutline,
  mdiArrowLeft,
  mdiArrowRight,
  mdiArrowTopRight,
  mdiBriefcaseCheckOutline,
  mdiBriefcaseOutline,
  mdiClockOutline,
  mdiConsoleNetworkOutline,
  mdiDownload,
  mdiDatabaseCogOutline,
  mdiEmailOutline,
  mdiFileAccountOutline,
  mdiFileDocumentEditOutline,
  mdiFileDocumentOutline,
  mdiGithub,
  mdiHarddisk,
  mdiHelpCircleOutline,
  mdiLayersTripleOutline,
  mdiLinkedin,
  mdiMapMarkerOutline,
  mdiMonitorDashboard,
  mdiPostOutline,
  mdiSchoolOutline,
  mdiServerNetwork,
  mdiStarFourPoints,
  mdiWeb,
} from "@mdi/js";

export const mdiIconPathByName: Record<string, string> = {
  "mdi-account-badge-outline": mdiAccountBadgeOutline,
  "mdi-account-group-outline": mdiAccountGroupOutline,
  "mdi-arrow-left": mdiArrowLeft,
  "mdi-arrow-right": mdiArrowRight,
  "mdi-arrow-top-right": mdiArrowTopRight,
  "mdi-briefcase-check-outline": mdiBriefcaseCheckOutline,
  "mdi-briefcase-outline": mdiBriefcaseOutline,
  "mdi-clock-outline": mdiClockOutline,
  "mdi-console-network-outline": mdiConsoleNetworkOutline,
  "mdi-database-cog-outline": mdiDatabaseCogOutline,
  "mdi-download": mdiDownload,
  "mdi-email-outline": mdiEmailOutline,
  "mdi-file-account-outline": mdiFileAccountOutline,
  "mdi-file-document-edit-outline": mdiFileDocumentEditOutline,
  "mdi-file-document-outline": mdiFileDocumentOutline,
  "mdi-github": mdiGithub,
  "mdi-harddisk": mdiHarddisk,
  "mdi-layers-triple-outline": mdiLayersTripleOutline,
  "mdi-linkedin": mdiLinkedin,
  "mdi-map-marker-outline": mdiMapMarkerOutline,
  "mdi-monitor-dashboard": mdiMonitorDashboard,
  "mdi-post-outline": mdiPostOutline,
  "mdi-school-outline": mdiSchoolOutline,
  "mdi-server-network": mdiServerNetwork,
  "mdi-star-four-points": mdiStarFourPoints,
  "mdi-web": mdiWeb,
};

export const mdiFallbackIconPath = mdiHelpCircleOutline;
